.PHONY: test vet lint integration integration-docker bench-integration

test:
	go test ./...

vet:
	go vet ./...

lint:
	golangci-lint run ./...

# Skip pull-heavy bench / singleflight cases here; use bench-integration.
integration:
	go test -tags integration -count=1 -timeout 20m -skip 'TestIntegrationBench|TestIntegrationPullSingleflight' ./...

integration-docker:
	go test -tags integration -count=1 -timeout 20m -run IntegrationDocker ./...

# This target intentionally includes the pull-heavy singleflight case;
# keep its root-module command in sync with docs/benchmarks.md.
bench-integration:
	go test -tags integration -count=1 -timeout 30m -run 'TestIntegrationBench|TestIntegrationPullSingleflight' ./...
	cd bench && go test -tags integration -count=1 -timeout 30m ./...
