.PHONY: test vet integration integration-docker

test:
	go test ./...

vet:
	go vet ./...

integration:
	go test -tags integration -count=1 -timeout 20m ./...

integration-docker:
	go test -tags integration -count=1 -timeout 20m -run IntegrationDocker ./...
